#!/bin/bash
# Manual testing guide for 3-peer sync
# This script provides instructions and helper commands for manual testing

set -e

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPTDIR"

echo "======================================"
echo "Task 5: Multi-Peer Sync Test"
echo "Manual Testing Guide"
echo "======================================"
echo ""
echo "This test requires 3 terminal windows to run peers in parallel."
echo ""
echo "Step 1: Compile binaries"
echo "  bash BUILD.sh"
echo ""
echo "Step 2: Open 3 terminals and run these commands:"
echo ""
echo "Terminal 1 (peer-1, bootstrap node):"
echo "  cd $SCRIPTDIR"
echo "  ADVPP_PEER_ID=peer-1 ADVPP_LISTEN=127.0.0.1:9000 ./chat-peer-1"
echo ""
echo "Terminal 2 (peer-2, bootstraps to peer-1):"
echo "  cd $SCRIPTDIR"
echo "  ADVPP_PEER_ID=peer-2 ADVPP_LISTEN=127.0.0.1:9001 ADVPP_BOOTSTRAP=127.0.0.1:9000 ./chat-peer-2"
echo ""
echo "Terminal 3 (peer-3, bootstraps to peer-1):"
echo "  cd $SCRIPTDIR"
echo "  ADVPP_PEER_ID=peer-3 ADVPP_LISTEN=127.0.0.1:9002 ADVPP_BOOTSTRAP=127.0.0.1:9000 ./chat-peer-3"
echo ""
echo "Step 3: Test message propagation"
echo ""
echo "In Terminal 1:"
echo "  Menu: 2 (Send message)"
echo "  Type: 'Hello from peer-1'"
echo "  Press Enter"
echo ""
echo "In Terminal 2:"
echo "  Menu: 1 (Read messages)"
echo "  Should see: 'peer-1 (...): Hello from peer-1'"
echo ""
echo "In Terminal 3:"
echo "  Menu: 1 (Read messages)"
echo "  Should see: 'peer-1 (...): Hello from peer-1'"
echo ""
echo "In Terminal 2:"
echo "  Menu: 2 (Send message)"
echo "  Type: 'Response from peer-2'"
echo "  Press Enter"
echo ""
echo "In Terminal 1:"
echo "  Menu: 1 (Read messages)"
echo "  Should see both messages in order:"
echo "  - 'peer-1 (...): Hello from peer-1'"
echo "  - 'peer-2 (...): Response from peer-2'"
echo ""
echo "Step 4: Verify convergence"
echo ""
echo "  Read on all 3 peers (menu option 1)"
echo "  All should show identical message histories"
echo "  No duplicates, same order"
echo ""
echo "Step 5: Test peer restart"
echo ""
echo "  Kill peer-1 (Ctrl+C in Terminal 1)"
echo "  Send a message from peer-2 (menu option 2)"
echo "  Restart peer-1"
echo "  Read messages in peer-1 (menu option 1)"
echo "  Should see the message sent while it was offline"
echo ""
